### ISSUE TITLE
Add support for pg 16

### ISSUE THREAD

**Issue by JaLe29** [liweiyi88/onedump#24]
I am using pg v 16 and after start I am getting an error:

```
Error: 1 error occurred:
        * failed to dump content to cache file: failed to dump file: command error: exit status 1, pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 16.0; pg_dump version: 15.5



local-dump failed, it took 181.169677ms with error: failed to dump content to cache file: failed to dump file: command error: exit status 1, pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 16.0; pg_dump version: 15.5
```

start cmd
```
sudo docker run --network host -v /home/jakub-desktop/git/evidia/jobs.yaml:/jobs.yaml julianli/onedump:v1.1.0-amd64 -f /jobs.yaml
```
job.yaml
```
jobs:
- name: local-dump
  dbdriver: postgresql
  dbdsn: postgres://postgres:xxxxxxxxxxxxxxxxxxxxxxx@localhost:5432/dev
  gzip: true
  storage:
    local:
      - path: ./postgresql-dump.sql
```

**Comment by liweiyi88** [comment]
@JaLe29 I am adding docker image support for a different version of Postgresql but docker image is not required for every use case 😄 . I would recommend just downloading the onedump binary from [relese](https://github.com/liweiyi88/onedump/releases/tag/v1.1.0) ,then install specific postgresql version on your local machine separately instead of using docker image.

I use docker image as I maintained a k8s cluster and you could also customise the docker image if you have your specific needs.

Lastly, I will update the docker image to support more mysql and postgresql versions anyway 😎

**Comment by liweiyi88** [comment]
This has been resolved by the latest version. To use postgresql 16 client, just run the command you mentioned in the issue `sudo docker run --network host -v /home/jakub-desktop/git/evidia/jobs.yaml:/jobs.yaml julianli/onedump:v1.1.0-amd64 -f /jobs.yaml` If you want to switch to postgresql15, then append `-e PG_VERSION=15`  to the docker run command.
